name: Python MCP Server CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      run: pip install uv
    - name: Sync dependencies
      run: uv sync
    - name: Install package in development mode and dev tools
      run: uv pip install -e .[dev]
    - name: Lint with flake8
      run: uv run flake8 . --count --statistics
    - name: Type check with mypy
      run: uv run mypy .
    - name: Test with pytest
      run: uv run pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
