name: Label Copilot Assigned Issues

on:
  issues:
    types: [assigned]

jobs:
  label-copilot-assignment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Add copilot label when assigned to Copilot
        if: github.event.assignee.login == 'copilot'
        uses: actions/github-script@v8
        with:
          script: |
            // Add "copilot" label when Copilot is assigned
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['copilot']
            });