name: Auto-assign Copilot Issues

on:
  issues:
    types: [labeled]

jobs:
  assign-to-copilot:
    if: github.event.label.name == 'copilot'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Assign issue to Copilot
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.issue;
            
            // Assign the issue to copilot user
            await github.rest.issues.addAssignees({
              ...issue,
              assignees: ['copilot']
            });
            
            // Add a comment confirming the assignment
            await github.rest.issues.createComment({
              ...issue,
              body: `🤖 This issue has been automatically assigned to @copilot for implementation.
              
              Copilot will follow the established patterns and guidelines in:
              - \`.github/copilot-instructions.md\`
              - \`docs/label-strategy.md\`
              
              Quality checks will be run before submitting a PR.`
            });